efutureassign/efutureassign/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrapapp.urls', namespace='scrapapp')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

efutureassign/scrapapp/urls.py
from django.urls import path

from .views import (dashboard_view, scrap_view) 

app_name = 'scrapapp'

urlpatterns = [
    path('', dashboard_view, name = 'dashboard'),
    path('managedata/', scrap_view, name = 'managedata'),

]

efutureassign/scrapapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class  Property(models.Model):
    title = models.CharField(max_length=200)
    facilites = models.CharField(max_length=150)
    price = models.FloatField(help_text='in LKR')
    distric = models.CharField(max_length=50, blank=True)
    datecreated = models.DateTimeField(auto_now_add=True)
    addedby = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id} - Added By {self.addedby.id}"

efutureassign/efutureassign/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

def logout_view(request):
    logout(request)
    return redirect('login')

def login_view(request):
    error_message = None
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                if request.GET.get('next'):
                    return redirect(request.GET.get('next'))
                else:
                    return redirect('scrapapp:dashboard')
        else:
            error_message = 'Ups.. Something Wrong..'

    context = {
        'form': form,
        'error_message': error_message
    }

    return render(request, 'auth/login.html', context)

efutureassign/scrapapp/views.py
from django.http import JsonResponse, response
from django.shortcuts import render

from urllib.parse import urlparse

from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from django.views.decorators.csrf import csrf_exempt

from scrapyd_api import ScrapydAPI


from .models import Property

from django.db import connection

# Create your views here.
@login_required
def dashboard_view(request):
    propertys = Property.objects.filter(addedby=request.user.id)

    cursor = connection.cursor()
    cursor.execute('''SELECT distric , avg(price)
        FROM scrapapp_property
        GROUP BY distric''')
    avgprice_with_distric = cursor.fetchall()

    cursor = connection.cursor()
    cursor.execute('''SELECT distric , count(price)
        FROM scrapapp_property
        GROUP BY distric''')
    num_of_props_per_distric = cursor.fetchall()

    return render(request, 'scrapapp/dashboard.html', {'propertys': propertys, 'awd':avgprice_with_distric, 'npd':  num_of_props_per_distric})

@csrf_exempt
def scrap_view(request):
    Property.objects.filter(addedby=request.user.id).delete()

    # connect scrapyd service
    scrapyd = ScrapydAPI('http://localhost:6800')

    # Initiate Scraping
    task = scrapyd.schedule('default', 'property', auth_user_id= request.user.id)

    return render(request, 'scrapapp/scrappage.html', {'task_id': task, 'status': 'started' })
    

efutureassign/scrapapp/templates/scrapapp/dashboard.html
{% extends 'base.html' %} {% block title %} Dashboard {% endblock title %}
{%block content %}
{% if propertys %}
<div class="row">
  <div class="col-6">
    <h3>Average Price against the Distric</h3>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Distric</th>
          <th scope="col">Average Price (Rs)</th>
        </tr>
      </thead>
      <tbody>
        {% for data in awd %}
          <tr>
            <td>{{data.0}}</td>
            <td>{{data.1|floatformat:"-1"}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="col-6">
    <h3>Properties to be sold against the Distric</h3>
        <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Distric</th>
          <th scope="col">Properties</th>
        </tr>
      </thead>
      <tbody>
        {% for data in npd %}
          <tr>
            <td>{{data.0}}</td>
            <td>{{data.1}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endif %}
<h3>Scrapped Data</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Distric</th>
      <th scope="col">Property</th>
      <th scope="col">Facilities</th>
      <th scope="col">Price</th>
    </tr>
  </thead>
  <tbody>
    {% if propertys %} {% for pos in propertys %}
    <tr>
      <th scope="row">{{pos.id}}</th>
      <td>{{pos.distric}}</td>
      <td>{{pos.title}}</td>
      <td>{{pos.facilites}}</td>
      <td>{{pos.price}}</td>
    </tr>
    {% endfor %} {% else %} No Scrapped Data Yet! {% endif %}
  </tbody>
</table>
{% endblock content %}

efutureassign/scrapapp/templates/scrapapp/scrappage.html
{% extends 'base.html' %}

{% block title %}
    Scrap Page
{% endblock title %}

{% block content %}
    <h3>Scrapping Started...</h3>
    <br>
    Go to Dash Board to see the scrapped data
    <br><br>
    <a href="{% url 'scrapapp:dashboard' %}" class="btn btn-danger">Go to Dash Board</a>
{% endblock content %}

efutureassign/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Analyzer | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="container mt-3 mb-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
  </body>
</html>

efutureassign/templates/navbar.html
{% load static %}
{% url 'scrapapp:dashboard' as path_to_dashboard %}
{% url 'scrapapp:managedata' as path_to_managedata %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href=""><img src="{% static 'logo.png' %}" class="logo-sm"></a>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_dashboard %}active{% endif %}" href={{path_to_dashboard}}>Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == path_to_managedata %}active{% endif %}" href={{path_to_managedata}}>Manage Data</a>
        </li>
      </ul>
    </div>
    {% if request.user.is_authenticated %}
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="#">Hi {{request.user}}!</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    {% endif %}
  </div>
</nav>